/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    pages: Page;
    products: Product;
    categories: Category;
    'menu-panels': MenuPanel;
    media: Media;
    testimonials: Testimonial;
    awards: Award;
    subscribers: Subscriber;
    backups: Backup;
    users: User;
    redirects: Redirect;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    pages: PagesSelect<false> | PagesSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    'menu-panels': MenuPanelsSelect<false> | MenuPanelsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    testimonials: TestimonialsSelect<false> | TestimonialsSelect<true>;
    awards: AwardsSelect<false> | AwardsSelect<true>;
    subscribers: SubscribersSelect<false> | SubscribersSelect<true>;
    backups: BackupsSelect<false> | BackupsSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    redirects: RedirectsSelect<false> | RedirectsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    header: Header;
    footer: Footer;
    design: Design;
    'site-settings': SiteSetting;
    'payload-jobs-stats': PayloadJobsStat;
  };
  globalsSelect: {
    header: HeaderSelect<false> | HeaderSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
    design: DesignSelect<false> | DesignSelect<true>;
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    'payload-jobs-stats': PayloadJobsStatsSelect<false> | PayloadJobsStatsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: {
      dailyBackup: TaskDailyBackup;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Всяка страница се сглобява от секции. Добавяйте, местете (с дръжката вляво) и триете секции свободно.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  _order?: string | null;
  title: string;
  /**
   * Само малки латински букви, цифри и тирета. Кирилицата се транслитерира, интервалите стават тирета, представки като „products/" се махат. Не е нужно да пишете пътя — само името.
   */
  slug: string;
  layout?:
    | (
        | {
            /**
             * Секцията остава тук, но не се показва на сайта.
             */
            hidden?: boolean | null;
            /**
             * Нула спира автоматичната смяна. Важи само при повече от един слайд.
             */
            autoplaySeconds?: number | null;
            slides?:
              | {
                  /**
                   * По избор. Малка картинка — в оригинала това е „30 дни гаранция за цената". Показва се с истинската си височина, до 40px.
                   */
                  badgeImage?: (number | null) | Media;
                  /**
                   * Малкият текст над заглавието. Напр. „Серия EcoFlow STREAM".
                   */
                  eyebrow?: string | null;
                  eyebrowColor?: ('white' | 'orange') | null;
                  heading?: string | null;
                  subheading?: string | null;
                  /**
                   * Напр. срок на промоцията: „5 – 31 август".
                   */
                  note?: string | null;
                  /**
                   * Препоръчително 2400×1000px. Текстът ляга върху него.
                   */
                  image?: (number | null) | Media;
                  /**
                   * По желание. Ако е празно, се ползва основното.
                   */
                  imageMobile?: (number | null) | Media;
                  cta?: {
                    label?: string | null;
                    /**
                     * Вътрешен път (/products) или пълен адрес към външния магазин.
                     */
                    url?: string | null;
                    newTab?: boolean | null;
                    /**
                     * Зависи от снимката отдолу. В оригинала бутоните върху банери са бели.
                     */
                    style?: ('light' | 'dark') | null;
                  };
                  align?: ('left' | 'center' | 'right') | null;
                  theme?: ('dark' | 'light') | null;
                  /**
                   * Увеличете, ако текстът не се чете добре върху снимката.
                   */
                  overlay?: ('none' | 'light' | 'medium' | 'strong') | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'heroBanner';
          }
        | {
            /**
             * Секцията остава тук, но не се показва на сайта.
             */
            hidden?: boolean | null;
            /**
             * Подредбата тук определя реда на екрана. Препоръчително 6–9 броя.
             */
            categories?: (number | Category)[] | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'categoryStrip';
          }
        | {
            /**
             * Секцията остава тук, но не се показва на сайта.
             */
            hidden?: boolean | null;
            sectionTitle?: string | null;
            subtitle?: string | null;
            products?: (number | Product)[] | null;
            cardStyle?: ('image' | 'price') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'productCarousel';
          }
        | {
            /**
             * Секцията остава тук, но не се показва на сайта.
             */
            hidden?: boolean | null;
            heading?: string | null;
            cards?:
              | {
                  /**
                   * Запълва цялата карта. Препоръчително 800×1000px (портрет).
                   */
                  image?: (number | null) | Media;
                  /**
                   * Малкият оранжев текст най-отгоре. Напр. „Ново" или „Горещо 🔥".
                   */
                  tag?: string | null;
                  heading?: string | null;
                  subheading?: string | null;
                  textTheme?: ('light' | 'dark') | null;
                  /**
                   * До два бутона на един ред под текста. Може и без нито един.
                   */
                  buttons?:
                    | {
                        label?: string | null;
                        url?: string | null;
                        style?: ('white' | 'outline' | 'black') | null;
                        id?: string | null;
                      }[]
                    | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'bannerCarousel';
          }
        | {
            /**
             * Секцията остава тук, но не се показва на сайта.
             */
            hidden?: boolean | null;
            /**
             * Напр. "Домашно резервно захранване".
             */
            sectionTitle?: string | null;
            showBanner?: boolean | null;
            banner?: {
              eyebrow?: string | null;
              eyebrowColor?: ('white' | 'orange') | null;
              heading?: string | null;
              subheading?: string | null;
              /**
               * Напр. "от 7 299 €" или "спестявате до 1 200 €".
               */
              priceNote?: string | null;
              /**
               * Препоръчително 2400×800px. Остава задължително и при видео — показва се, докато то се зареди.
               */
              image?: (number | null) | Media;
              /**
               * По избор. MP4 (H.264), 1920px широчина, без звук, до 20 MB. Върти се само, без бутони. При включена системна настройка за намалено движение се показва снимката.
               */
              video?: (number | null) | Media;
              cta?: {
                label?: string | null;
                /**
                 * Вътрешен път (/products) или пълен адрес към външния магазин.
                 */
                url?: string | null;
                newTab?: boolean | null;
                /**
                 * Зависи от снимката отдолу. В оригинала бутоните върху банери са бели.
                 */
                style?: ('light' | 'dark') | null;
              };
              theme?: ('dark' | 'light') | null;
            };
            /**
             * Подредбата тук определя реда на екрана. Препоръчително 4–5 броя — на широк екран се показват пет колони.
             */
            products?: (number | Product)[] | null;
            showMoreTile?: boolean | null;
            moreTile?: {
              label?: string | null;
              url?: string | null;
              /**
               * В оригинала това е групова снимка на продуктите от серията.
               */
              image?: (number | null) | Media;
              description?: string | null;
              secondaryLabel?: string | null;
              secondaryUrl?: string | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'bannerProductRow';
          }
        | {
            /**
             * Секцията остава тук, но не се показва на сайта.
             */
            hidden?: boolean | null;
            sectionTitle?: string | null;
            cards?:
              | {
                  heading?: string | null;
                  description?: string | null;
                  image?: (number | null) | Media;
                  cta?: {
                    label?: string | null;
                    /**
                     * Вътрешен път (/products) или пълен адрес към външния магазин.
                     */
                    url?: string | null;
                    newTab?: boolean | null;
                    /**
                     * Зависи от снимката отдолу. В оригинала бутоните върху банери са бели.
                     */
                    style?: ('light' | 'dark') | null;
                  };
                  theme?: ('dark' | 'light') | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'promoCards';
          }
        | {
            /**
             * Секцията остава тук, но не се показва на сайта.
             */
            hidden?: boolean | null;
            /**
             * По избор. В оригинала някои банери са без заглавие над тях.
             */
            sectionTitle?: string | null;
            eyebrow?: string | null;
            eyebrowColor?: ('white' | 'orange') | null;
            heading?: string | null;
            subheading?: string | null;
            /**
             * По избор. Напр. „от 1199 €". Празно поле не показва нищо.
             */
            priceNote?: string | null;
            image?: (number | null) | Media;
            cta?: {
              label?: string | null;
              /**
               * Вътрешен път (/products) или пълен адрес към външния магазин.
               */
              url?: string | null;
              newTab?: boolean | null;
              /**
               * Зависи от снимката отдолу. В оригинала бутоните върху банери са бели.
               */
              style?: ('light' | 'dark') | null;
            };
            align?: ('left' | 'center' | 'right') | null;
            theme?: ('dark' | 'light') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'wideBanner';
          }
        | {
            /**
             * Секцията остава тук, но не се показва на сайта.
             */
            hidden?: boolean | null;
            sectionTitle?: string | null;
            items?:
              | {
                  icon?: ('shield' | 'globe' | 'card' | 'support' | 'return' | 'truck' | 'bolt' | 'certificate') | null;
                  title?: string | null;
                  description?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'benefitsGrid';
          }
        | {
            /**
             * Секцията остава тук, но не се показва на сайта.
             */
            hidden?: boolean | null;
            sectionTitle?: string | null;
            testimonials?: (number | Testimonial)[] | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'testimonialsBlock';
          }
        | {
            /**
             * Секцията остава тук, но не се показва на сайта.
             */
            hidden?: boolean | null;
            sectionTitle?: string | null;
            awards?: (number | Award)[] | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'logoWall';
          }
      )[]
    | null;
  metaTitle?: string | null;
  metaDescription?: string | null;
  metaImage?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Описание на изображението за екранни четци и SEO. Задължително.
   */
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    banner?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    wide?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    content?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    large?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    full?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * Категориите са на три нива: главна категория („Портативни електроцентрали") → серия („DELTA серия") → подсерия („DELTA 3 серия"). Всяко ниво се закача към горното с полето „Подкатегория на". Продуктът се слага в най-долното ниво, което го описва.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  _order?: string | null;
  title: string;
  /**
   * Само малки латински букви, цифри и тирета. Кирилицата се транслитерира, интервалите стават тирета, представки като „products/" се махат. Не е нужно да пишете пътя — само името.
   */
  slug: string;
  /**
   * Празно = главна категория. Изберете главна, за да стане серия; изберете серия, за да стане подсерия. Подсерията няма собствена страница — показва се като раздел на страницата на серията.
   */
  parent?: (number | null) | Category;
  /**
   * Отнася се за лентата с икони на началната страница.
   */
  showInStrip?: boolean | null;
  /**
   * По избор. Показва се в червено под името в лентата с категории. Напр. „Ново".
   */
  stripBadge?: string | null;
  /**
   * За лентата с категории. Препоръчително 160×160px.
   */
  icon?: (number | null) | Media;
  /**
   * Банерът най-отгоре на страницата. Препоръчително 2400×800px.
   */
  heroImage?: (number | null) | Media;
  heroTagline?: string | null;
  /**
   * По избор. Показва се между описанието и продуктите. Препоръчително 2400×800px.
   */
  banner?: (number | null) | Media;
  /**
   * Кратък въвеждащ текст под името на категорията. Ползва се и като описание за търсачки, ако полето в раздел SEO е празно.
   */
  description?: string | null;
  layout?:
    | (
        | {
            /**
             * Секцията остава тук, но не се показва на сайта.
             */
            hidden?: boolean | null;
            /**
             * Нула спира автоматичната смяна. Важи само при повече от един слайд.
             */
            autoplaySeconds?: number | null;
            slides?:
              | {
                  /**
                   * По избор. Малка картинка — в оригинала това е „30 дни гаранция за цената". Показва се с истинската си височина, до 40px.
                   */
                  badgeImage?: (number | null) | Media;
                  /**
                   * Малкият текст над заглавието. Напр. „Серия EcoFlow STREAM".
                   */
                  eyebrow?: string | null;
                  eyebrowColor?: ('white' | 'orange') | null;
                  heading?: string | null;
                  subheading?: string | null;
                  /**
                   * Напр. срок на промоцията: „5 – 31 август".
                   */
                  note?: string | null;
                  /**
                   * Препоръчително 2400×1000px. Текстът ляга върху него.
                   */
                  image?: (number | null) | Media;
                  /**
                   * По желание. Ако е празно, се ползва основното.
                   */
                  imageMobile?: (number | null) | Media;
                  cta?: {
                    label?: string | null;
                    /**
                     * Вътрешен път (/products) или пълен адрес към външния магазин.
                     */
                    url?: string | null;
                    newTab?: boolean | null;
                    /**
                     * Зависи от снимката отдолу. В оригинала бутоните върху банери са бели.
                     */
                    style?: ('light' | 'dark') | null;
                  };
                  align?: ('left' | 'center' | 'right') | null;
                  theme?: ('dark' | 'light') | null;
                  /**
                   * Увеличете, ако текстът не се чете добре върху снимката.
                   */
                  overlay?: ('none' | 'light' | 'medium' | 'strong') | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'heroBanner';
          }
        | {
            /**
             * Секцията остава тук, но не се показва на сайта.
             */
            hidden?: boolean | null;
            /**
             * Подредбата тук определя реда на екрана. Препоръчително 6–9 броя.
             */
            categories?: (number | Category)[] | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'categoryStrip';
          }
        | {
            /**
             * Секцията остава тук, но не се показва на сайта.
             */
            hidden?: boolean | null;
            sectionTitle?: string | null;
            subtitle?: string | null;
            products?: (number | Product)[] | null;
            cardStyle?: ('image' | 'price') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'productCarousel';
          }
        | {
            /**
             * Секцията остава тук, но не се показва на сайта.
             */
            hidden?: boolean | null;
            heading?: string | null;
            cards?:
              | {
                  /**
                   * Запълва цялата карта. Препоръчително 800×1000px (портрет).
                   */
                  image?: (number | null) | Media;
                  /**
                   * Малкият оранжев текст най-отгоре. Напр. „Ново" или „Горещо 🔥".
                   */
                  tag?: string | null;
                  heading?: string | null;
                  subheading?: string | null;
                  textTheme?: ('light' | 'dark') | null;
                  /**
                   * До два бутона на един ред под текста. Може и без нито един.
                   */
                  buttons?:
                    | {
                        label?: string | null;
                        url?: string | null;
                        style?: ('white' | 'outline' | 'black') | null;
                        id?: string | null;
                      }[]
                    | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'bannerCarousel';
          }
        | {
            /**
             * Секцията остава тук, но не се показва на сайта.
             */
            hidden?: boolean | null;
            /**
             * Напр. "Домашно резервно захранване".
             */
            sectionTitle?: string | null;
            showBanner?: boolean | null;
            banner?: {
              eyebrow?: string | null;
              eyebrowColor?: ('white' | 'orange') | null;
              heading?: string | null;
              subheading?: string | null;
              /**
               * Напр. "от 7 299 €" или "спестявате до 1 200 €".
               */
              priceNote?: string | null;
              /**
               * Препоръчително 2400×800px. Остава задължително и при видео — показва се, докато то се зареди.
               */
              image?: (number | null) | Media;
              /**
               * По избор. MP4 (H.264), 1920px широчина, без звук, до 20 MB. Върти се само, без бутони. При включена системна настройка за намалено движение се показва снимката.
               */
              video?: (number | null) | Media;
              cta?: {
                label?: string | null;
                /**
                 * Вътрешен път (/products) или пълен адрес към външния магазин.
                 */
                url?: string | null;
                newTab?: boolean | null;
                /**
                 * Зависи от снимката отдолу. В оригинала бутоните върху банери са бели.
                 */
                style?: ('light' | 'dark') | null;
              };
              theme?: ('dark' | 'light') | null;
            };
            /**
             * Подредбата тук определя реда на екрана. Препоръчително 4–5 броя — на широк екран се показват пет колони.
             */
            products?: (number | Product)[] | null;
            showMoreTile?: boolean | null;
            moreTile?: {
              label?: string | null;
              url?: string | null;
              /**
               * В оригинала това е групова снимка на продуктите от серията.
               */
              image?: (number | null) | Media;
              description?: string | null;
              secondaryLabel?: string | null;
              secondaryUrl?: string | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'bannerProductRow';
          }
        | {
            /**
             * Секцията остава тук, но не се показва на сайта.
             */
            hidden?: boolean | null;
            sectionTitle?: string | null;
            cards?:
              | {
                  heading?: string | null;
                  description?: string | null;
                  image?: (number | null) | Media;
                  cta?: {
                    label?: string | null;
                    /**
                     * Вътрешен път (/products) или пълен адрес към външния магазин.
                     */
                    url?: string | null;
                    newTab?: boolean | null;
                    /**
                     * Зависи от снимката отдолу. В оригинала бутоните върху банери са бели.
                     */
                    style?: ('light' | 'dark') | null;
                  };
                  theme?: ('dark' | 'light') | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'promoCards';
          }
        | {
            /**
             * Секцията остава тук, но не се показва на сайта.
             */
            hidden?: boolean | null;
            /**
             * По избор. В оригинала някои банери са без заглавие над тях.
             */
            sectionTitle?: string | null;
            eyebrow?: string | null;
            eyebrowColor?: ('white' | 'orange') | null;
            heading?: string | null;
            subheading?: string | null;
            /**
             * По избор. Напр. „от 1199 €". Празно поле не показва нищо.
             */
            priceNote?: string | null;
            image?: (number | null) | Media;
            cta?: {
              label?: string | null;
              /**
               * Вътрешен път (/products) или пълен адрес към външния магазин.
               */
              url?: string | null;
              newTab?: boolean | null;
              /**
               * Зависи от снимката отдолу. В оригинала бутоните върху банери са бели.
               */
              style?: ('light' | 'dark') | null;
            };
            align?: ('left' | 'center' | 'right') | null;
            theme?: ('dark' | 'light') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'wideBanner';
          }
        | {
            /**
             * Секцията остава тук, но не се показва на сайта.
             */
            hidden?: boolean | null;
            sectionTitle?: string | null;
            items?:
              | {
                  icon?: ('shield' | 'globe' | 'card' | 'support' | 'return' | 'truck' | 'bolt' | 'certificate') | null;
                  title?: string | null;
                  description?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'benefitsGrid';
          }
        | {
            /**
             * Секцията остава тук, но не се показва на сайта.
             */
            hidden?: boolean | null;
            sectionTitle?: string | null;
            testimonials?: (number | Testimonial)[] | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'testimonialsBlock';
          }
        | {
            /**
             * Секцията остава тук, но не се показва на сайта.
             */
            hidden?: boolean | null;
            sectionTitle?: string | null;
            awards?: (number | Award)[] | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'logoWall';
          }
      )[]
    | null;
  metaTitle?: string | null;
  metaDescription?: string | null;
  /**
   * Включи за категории с под 3 продукта или без собствен текст — да не се индексират като празни страници. Страницата остава достъпна; само излиза от sitemap.xml и получава noindex.
   */
  noindex?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Продуктовата страница се сглобява от секции, също като обикновените страници. Продукт без добавени секции показва галерия, цена, бутон и описание.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: number;
  _order?: string | null;
  title: string;
  /**
   * Само малки латински букви, цифри и тирета. Кирилицата се транслитерира, интервалите стават тирета, представки като „products/" се махат. Не е нужно да пишете пътя — само името.
   */
  slug: string;
  /**
   * Номерът на артикула в dice.bg. Служи за сверяване при внос и за търсачките.
   */
  sku?: string | null;
  /**
   * Обикновено EcoFlow. Сменя се при аксесоари на друг производител — в каталога има артикули на Anker, VEMARK, 4smarts и други.
   */
  brand?: string | null;
  /**
   * Основният баркод на производителя, 13 цифри. Влиза в данните за търсачките и позволява на Google да разпознае продукта еднозначно.
   */
  ean?: string | null;
  /**
   * За комплекти с две устройства. По избор.
   */
  ean2?: string | null;
  /**
   * Складов или доставчиков номер. Служи за сверяване при внос и не се показва никъде на сайта.
   */
  barcodeInternal?: string | null;
  category: number | Category;
  /**
   * Попълва се само — взима се от избраната по-горе категория.
   */
  categoryName?: string | null;
  categorySlug?: string | null;
  categoryParentSlug?: string | null;
  categoryGrandparentSlug?: string | null;
  /**
   * Редът под името в продуктовата карта. Напр. "6144Wh капацитет / 7200W изход".
   */
  tagline?: string | null;
  /**
   * От 0 до 5, през 0,5. Празно = не се показва.
   */
  rating?: number | null;
  /**
   * Попълва се само при реални отзиви за този продукт.
   */
  reviewCount?: number | null;
  /**
   * Кратките изречения в кутията за покупка, под цената. Три до шест са достатъчни — това е първото, което клиентът чете.
   */
  highlights?:
    | {
        title: string;
        /**
         * По избор. Празно — акцентът е само заглавието, на един ред.
         */
        text?: string | null;
        id?: string | null;
      }[]
    | null;
  badge?: ('none' | 'new' | 'sale' | 'bestseller' | 'limited') | null;
  /**
   * Служи само за подреждане и филтриране на списъка тук. Не влияе на изгледа на страницата — той зависи единствено от добавените секции.
   */
  productType?: ('hero' | 'accessory') | null;
  /**
   * Цената в евро. Левовата равностойност се изчислява автоматично по фиксирания курс 1.95583.
   */
  price: number;
  /**
   * Ако е попълнена, се показва зачертана до текущата цена.
   */
  compareAtPrice?: number | null;
  /**
   * Пълен адрес към продуктовата страница във външния магазин, където се извършва покупката.
   */
  externalUrl: string;
  ctaLabel?: string | null;
  availability?: ('in-stock' | 'preorder' | 'out-of-stock') | null;
  image: number | Media;
  gallery?:
    | {
        image: number | Media;
        id?: string | null;
      }[]
    | null;
  /**
   * Избери серии или конкретни модели, с които работи. Показва се на страницата на серията и в „Свързани продукти" на модела.
   */
  compatibleWith?:
    | (
        | {
            relationTo: 'categories';
            value: number | Category;
          }
        | {
            relationTo: 'products';
            value: number | Product;
          }
      )[]
    | null;
  /**
   * Оригиналът показва спецификациите като плосък списък. Групите са наша добавка — при 30+ реда плоският списък е нечетим. Заглавието на групата е по избор: оставите ли го празно, редовете се сливат с предишната група.
   */
  specGroups?:
    | {
        /**
         * Напр. Изход променлив ток. Може да остане празно.
         */
        groupLabel?: string | null;
        rows?:
          | {
              label: string;
              value: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Не въвеждайте тук. Полето е пренесено в „Спецификации по групи" и предстои да бъде премахнато.
   */
  specs?:
    | {
        label: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  description?: string | null;
  /**
   * Ако е празно, се ползва името на продукта.
   */
  metaTitle?: string | null;
  /**
   * Ако е празно, се ползва кратката спецификация.
   */
  metaDescription?: string | null;
  sections?:
    | (
        | {
            /**
             * Ако попълните, секцията се появява в закаченото меню най-горе. Оставете празно, за да не се показва.
             */
            anchorLabel?: string | null;
            items?:
              | {
                  /**
                   * Едрият текст. Напр. 1024Wh.
                   */
                  value: string;
                  /**
                   * Дребният текст отдолу. Напр. Капацитет.
                   */
                  label: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'keySpecStrip';
          }
        | {
            /**
             * Ако попълните, секцията се появява в закаченото меню най-горе. Оставете празно, за да не се показва.
             */
            anchorLabel?: string | null;
            /**
             * По избор. Празно заглавие дава секция само със снимката — така е главният банер в оригинала, чието заглавие стои на следващата секция.
             */
            heading?: string | null;
            subheading?: string | null;
            subheadingPosition?: ('above' | 'below') | null;
            body?: string | null;
            /**
             * Препоръчително 1680px широчина, както в оригинала.
             */
            image: number | Media;
            /**
             * За снимка, която сама съдържа текст или графики — колаж, екрани от приложение — изберете „Текст отгоре, снимка отдолу". Тогава снимката се показва цяла, без изрязване и без слой върху нея.
             */
            layout?: ('image-right' | 'image-left' | 'stacked' | 'image-full') | null;
            theme?: ('light' | 'dark') | null;
            /**
             * По избор. Напр. 3600W и под него — пикова мощност.
             */
            stats?:
              | {
                  value: string;
                  label: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'featureSection';
          }
        | {
            /**
             * Ако попълните, секцията се появява в закаченото меню най-горе. Оставете празно, за да не се показва.
             */
            anchorLabel?: string | null;
            heading?: string | null;
            /**
             * По избор. Показва се при всички подредби, центриран под заглавието — както текстът в секция с изображение.
             */
            intro?: string | null;
            /**
             * При „снимка с панел отстрани" се показват редовете със стойности вдясно от снимката. При „снимка отгоре" редовете не се показват — под разделите излиза само текстът от полето „Текст под разделите". При „раздели над снимката" разделите са центрирани над снимката, а текстът под разделите не се показва.
             */
            layout?: ('side-panel' | 'image-top' | 'tabs-top') | null;
            tabs?:
              | {
                  label: string;
                  image: number | Media;
                  /**
                   * Показва се само при подредба „снимка отгоре". Едно изречение под лентата с разделите. Празно поле не показва нищо. Полето се пази и при другите подредби.
                   */
                  caption?: string | null;
                  rows?:
                    | {
                        /**
                         * По избор. Малка иконка вляво от реда.
                         */
                        icon?: (number | null) | Media;
                        /**
                         * Напр. лампа за къмпинг, или: от контакт.
                         */
                        label: string;
                        /**
                         * Напр. 10 W или 1400W.
                         */
                        sublabel?: string | null;
                        /**
                         * Напр. 58 ч или 45 мин. Взима се от официален източник — не се пресмята.
                         */
                        value: string;
                        id?: string | null;
                      }[]
                    | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'tabbedShowcase';
          }
        | {
            /**
             * Ако попълните, секцията се появява в закаченото меню най-горе. Оставете празно, за да не се показва.
             */
            anchorLabel?: string | null;
            heading?: string | null;
            options?:
              | {
                  /**
                   * Напр. самостоятелно, или: с панел 220W.
                   */
                  label: string;
                  price: number;
                  /**
                   * Отстъпката се смята от двете цени.
                   */
                  comparePrice?: number | null;
                  /**
                   * Адресът на този вариант в магазина.
                   */
                  externalUrl?: string | null;
                  /**
                   * Ако вариантът е отделен продукт в нашия каталог.
                   */
                  product?: (number | null) | Product;
                  isCurrent?: boolean | null;
                  soldOut?: boolean | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'bundleOptions';
          }
        | {
            /**
             * Ако попълните, секцията се появява в закаченото меню най-горе. Оставете празно, за да не се показва.
             */
            anchorLabel?: string | null;
            heading?: string | null;
            /**
             * По избор. Центриран текст между заглавието и таблицата.
             */
            intro?: string | null;
            /**
             * Всяка колона е един модел. Редовете по-долу трябва да са в същия ред.
             */
            columns?:
              | {
                  /**
                   * Ако моделът е в нашия каталог, останалото се допълва от него.
                   */
                  product?: (number | null) | Product;
                  /**
                   * Ползва се, когато моделът не е в каталога ни.
                   */
                  label?: string | null;
                  /**
                   * По избор. Ако е празно, се взима от продукта.
                   */
                  image?: (number | null) | Media;
                  /**
                   * Напр. най-изгодният за туризъм.
                   */
                  tagline?: string | null;
                  price?: number | null;
                  comparePrice?: number | null;
                  ctaLabel?: string | null;
                  ctaUrl?: string | null;
                  highlight?: boolean | null;
                  id?: string | null;
                }[]
              | null;
            /**
             * Всеки ред е един показател. Стойностите се въвеждат по една за колона.
             */
            rows?:
              | {
                  /**
                   * Напр. капацитет, изход променлив ток, тегло.
                   */
                  label: string;
                  /**
                   * По една за всяка колона, в същия ред като колоните по-горе.
                   */
                  values?:
                    | {
                        value?: string | null;
                        id?: string | null;
                      }[]
                    | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'comparisonTable';
          }
        | {
            /**
             * Ако попълните, секцията се появява в закаченото меню най-горе. Оставете празно, за да не се показва.
             */
            anchorLabel?: string | null;
            heading?: string | null;
            /**
             * Ползва се, когато няма раздели по-долу.
             */
            items?:
              | {
                  image?: (number | null) | Media;
                  /**
                   * Напр. кабел за зареждане.
                   */
                  name: string;
                  qty?: number | null;
                  id?: string | null;
                }[]
              | null;
            /**
             * По избор. С попълнени раздели списъкът „Съдържание" по-горе НЕ се показва.
             */
            groups?:
              | {
                  label: string;
                  items?:
                    | {
                        image?: (number | null) | Media;
                        /**
                         * Напр. кабел за зареждане.
                         */
                        name: string;
                        qty?: number | null;
                        id?: string | null;
                      }[]
                    | null;
                  id?: string | null;
                }[]
              | null;
            /**
             * Номер на раздела, който е отворен при зареждане — първият е 0. Празно значи първия.
             */
            defaultGroup?: number | null;
            /**
             * По избор.
             */
            caption?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'inTheBox';
          }
        | {
            /**
             * Ако попълните, секцията се появява в закаченото меню най-горе. Оставете празно, за да не се показва.
             */
            anchorLabel?: string | null;
            /**
             * Съдържанието идва от раздел „Спецификации" на продукта — тук не се въвежда нищо.
             */
            heading?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'specTable';
          }
        | {
            /**
             * Ако попълните, секцията се появява в закаченото меню най-горе. Оставете празно, за да не се показва.
             */
            anchorLabel?: string | null;
            heading?: string | null;
            items?:
              | {
                  question: string;
                  answer: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'faqBlock';
          }
        | {
            /**
             * Ако попълните, секцията се появява в закаченото меню най-горе. Оставете празно, за да не се показва.
             */
            anchorLabel?: string | null;
            heading?: string | null;
            /**
             * Автоматично: аксесоарите, при които в „Съвместим с" е избран този продукт или неговата серия. Ръчно: списъкът по-долу.
             */
            mode?: ('auto' | 'manual') | null;
            /**
             * Подредбата тук е подредбата на екрана.
             */
            products?: (number | Product)[] | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'relatedProducts';
          }
        | {
            /**
             * Ако попълните, секцията се появява в закаченото меню най-горе. Оставете празно, за да не се показва.
             */
            anchorLabel?: string | null;
            /**
             * Номерацията се слага автоматично по реда тук.
             */
            items?:
              | {
                  text: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'footnotes';
          }
        | {
            /**
             * Ако попълните, секцията се появява в закаченото меню най-горе. Оставете празно, за да не се показва.
             */
            anchorLabel?: string | null;
            heading?: string | null;
            body?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            /**
             * Разгъва се при клик върху заглавието.
             */
            collapsed?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'legalText';
          }
      )[]
    | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials".
 */
export interface Testimonial {
  id: number;
  _order?: string | null;
  author: string;
  location?: string | null;
  quote: string;
  image?: (number | null) | Media;
  rating?: number | null;
  link?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "awards".
 */
export interface Award {
  id: number;
  _order?: string | null;
  name: string;
  /**
   * Прозрачен PNG или SVG. Показва се в секцията "Отличени от".
   */
  logo: number | Media;
  url?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Всеки панел е това, което се показва вдясно в мега менюто, когато потребителят посочи подточка от сайдбара. Тук се сменят снимките и картите.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "menu-panels".
 */
export interface MenuPanel {
  id: number;
  _order?: string | null;
  /**
   * Текстът, който се вижда в сайдбара. Напр. „Серия EcoFlow DELTA". При автоматичен режим може да е празно — тогава се взима името на категорията.
   */
  title?: string | null;
  /**
   * Само малки латински букви, цифри и тирета. Кирилицата се транслитерира, интервалите стават тирета, представки като „products/" се махат. Не е нужно да пишете пътя — само името.
   */
  slug: string;
  /**
   * Автоматично: продуктите на избраната категория се показват сами — първите седем, голяма първа карта, „Виж всички" към категорията. Ръчен избор: секциите и картите по-долу се попълват на ръка.
   */
  mode?: ('auto' | 'manual') | null;
  /**
   * Продуктите ѝ се показват в панела. Ако е празно, панелът се държи като ръчен.
   */
  category?: (number | null) | Category;
  /**
   * Всяка секция е един ред със заглавие, линк „Виж всички" вдясно и мрежа с продукти. В референтния дизайн панелът има две секции — продукти и аксесоари.
   */
  sections?:
    | {
        heading: string;
        /**
         * Страницата, към която водят линкът „Виж всички" и плочката в края на мрежата. Адресът се извежда от категорията.
         */
        viewAllCategory?: (number | null) | Category;
        viewAllLabel?: string | null;
        /**
         * Ползва се само ако е попълнен — вместо категорията по-горе.
         */
        viewAllUrl?: string | null;
        /**
         * Заема цялата височина на мрежата. Оставете името и продукта празни, за да я скриете.
         */
        featured?: {
          /**
           * По избор. Снимката, името, редът със спецификации и адресът се взимат от продукта. Полетата по-долу ги заменят, ако са попълнени.
           */
          product?: (number | null) | Product;
          /**
           * По избор. Ако е празно, се взима главната снимка на продукта. Продуктова снимка на прозрачен фон, препоръчително 600×600px.
           */
          image?: (number | null) | Media;
          /**
           * По избор. Ако е празно, се взима от продукта.
           */
          title?: string | null;
          /**
           * По избор. Ако е празно, се взима от продукта (кратката спецификация). Сивият текст под името, напр. „1024Wh капацитет | 1800W изход | LFP".
           */
          specLine?: string | null;
          /**
           * По избор. Ако е празно, води към страницата на продукта.
           */
          url?: string | null;
          /**
           * По избор. Малък син надпис над името, напр. „Ново". Етикетът на продукта НЕ се пренася сам — вие решавате къде да има етикет.
           */
          label?: string | null;
          /**
           * Оранжев бадж в ъгъла на снимката. Напр. „ПОДАРЪК".
           */
          ribbon?: string | null;
        };
        /**
         * До 5 карти, ако плочката „Виж всички" е включена, иначе до 6. Подредбата тук е подредбата на екрана.
         */
        cards?:
          | {
              /**
               * По избор. Снимката, името, редът със спецификации и адресът се взимат от продукта. Полетата по-долу ги заменят, ако са попълнени.
               */
              product?: (number | null) | Product;
              /**
               * По избор. Ако е празно, се взима главната снимка на продукта. Продуктова снимка на прозрачен фон, препоръчително 600×600px.
               */
              image?: (number | null) | Media;
              /**
               * По избор при избран продукт — тогава се взима името му. Задължително без продукт.
               */
              title?: string | null;
              /**
               * По избор. Ако е празно, се взима от продукта (кратката спецификация). Сивият текст под името, напр. „1024Wh капацитет | 1800W изход | LFP".
               */
              specLine?: string | null;
              /**
               * По избор. Ако е празно, води към страницата на продукта.
               */
              url?: string | null;
              /**
               * По избор. Малък син надпис над името, напр. „Ново". Етикетът на продукта НЕ се пренася сам — вие решавате къде да има етикет.
               */
              label?: string | null;
              /**
               * Оранжев бадж в ъгъла на снимката. Напр. „ПОДАРЪК".
               */
              ribbon?: string | null;
              id?: string | null;
            }[]
          | null;
        showViewAllTile?: boolean | null;
        /**
         * Празно — плочката води към категорията по-горе.
         */
        viewAllTileUrl?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Хората, абонирани за бюлетина през формата на сайта. Бутонът „Изтегли CSV" е над списъка.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "subscribers".
 */
export interface Subscriber {
  id: number;
  email: string;
  subscribedAt?: string | null;
  status?: ('active' | 'unsubscribed') | null;
  /**
   * Страницата, от която е дошъл абонатът.
   */
  source?: string | null;
  /**
   * Изисква се от ЗЗЛД. Записва се какво е отметнал абонатът в момента на абонирането — не се пипа после.
   */
  consent?: boolean | null;
  note?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Всеки архив съдържа базата и качените снимки. Бутонът „Създай архив сега“ е над списъка. Свалете копие на компютъра си — архивите тук лежат на същия диск и не пазят от отказ на хардуера.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "backups".
 */
export interface Backup {
  id: number;
  /**
   * За какво е този архив. Напр. „Преди пренареждане на менюто“.
   */
  label: string;
  trigger?: ('ръчно' | 'по график' | 'качен') | null;
  includesMedia?: boolean | null;
  mediaFiles?: number | null;
  /**
   * Защитените архиви не се трият от автоматичното чистене, което пази последните 10. Архивите преди миграция се отбелязват така сами.
   */
  protected?: boolean | null;
  note?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * Стари адреси, които водят към новите. Попълва се само — при смяна на категория или на адрес на продукт. Ред се трие само ако старият адрес вече не трябва да работи.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects".
 */
export interface Redirect {
  id: number;
  /**
   * Пътят без домейна, напр. /products/delta-3.
   */
  from: string;
  to: string;
  /**
   * Какво е предизвикало пренасочването — за четене от човек.
   */
  reason?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: number;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'dailyBackup';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?: ('inline' | 'dailyBackup') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  meta?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'products';
        value: number | Product;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'menu-panels';
        value: number | MenuPanel;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'testimonials';
        value: number | Testimonial;
      } | null)
    | ({
        relationTo: 'awards';
        value: number | Award;
      } | null)
    | ({
        relationTo: 'subscribers';
        value: number | Subscriber;
      } | null)
    | ({
        relationTo: 'backups';
        value: number | Backup;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'redirects';
        value: number | Redirect;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  _order?: T;
  title?: T;
  slug?: T;
  layout?:
    | T
    | {
        heroBanner?:
          | T
          | {
              hidden?: T;
              autoplaySeconds?: T;
              slides?:
                | T
                | {
                    badgeImage?: T;
                    eyebrow?: T;
                    eyebrowColor?: T;
                    heading?: T;
                    subheading?: T;
                    note?: T;
                    image?: T;
                    imageMobile?: T;
                    cta?:
                      | T
                      | {
                          label?: T;
                          url?: T;
                          newTab?: T;
                          style?: T;
                        };
                    align?: T;
                    theme?: T;
                    overlay?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        categoryStrip?:
          | T
          | {
              hidden?: T;
              categories?: T;
              id?: T;
              blockName?: T;
            };
        productCarousel?:
          | T
          | {
              hidden?: T;
              sectionTitle?: T;
              subtitle?: T;
              products?: T;
              cardStyle?: T;
              id?: T;
              blockName?: T;
            };
        bannerCarousel?:
          | T
          | {
              hidden?: T;
              heading?: T;
              cards?:
                | T
                | {
                    image?: T;
                    tag?: T;
                    heading?: T;
                    subheading?: T;
                    textTheme?: T;
                    buttons?:
                      | T
                      | {
                          label?: T;
                          url?: T;
                          style?: T;
                          id?: T;
                        };
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        bannerProductRow?:
          | T
          | {
              hidden?: T;
              sectionTitle?: T;
              showBanner?: T;
              banner?:
                | T
                | {
                    eyebrow?: T;
                    eyebrowColor?: T;
                    heading?: T;
                    subheading?: T;
                    priceNote?: T;
                    image?: T;
                    video?: T;
                    cta?:
                      | T
                      | {
                          label?: T;
                          url?: T;
                          newTab?: T;
                          style?: T;
                        };
                    theme?: T;
                  };
              products?: T;
              showMoreTile?: T;
              moreTile?:
                | T
                | {
                    label?: T;
                    url?: T;
                    image?: T;
                    description?: T;
                    secondaryLabel?: T;
                    secondaryUrl?: T;
                  };
              id?: T;
              blockName?: T;
            };
        promoCards?:
          | T
          | {
              hidden?: T;
              sectionTitle?: T;
              cards?:
                | T
                | {
                    heading?: T;
                    description?: T;
                    image?: T;
                    cta?:
                      | T
                      | {
                          label?: T;
                          url?: T;
                          newTab?: T;
                          style?: T;
                        };
                    theme?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        wideBanner?:
          | T
          | {
              hidden?: T;
              sectionTitle?: T;
              eyebrow?: T;
              eyebrowColor?: T;
              heading?: T;
              subheading?: T;
              priceNote?: T;
              image?: T;
              cta?:
                | T
                | {
                    label?: T;
                    url?: T;
                    newTab?: T;
                    style?: T;
                  };
              align?: T;
              theme?: T;
              id?: T;
              blockName?: T;
            };
        benefitsGrid?:
          | T
          | {
              hidden?: T;
              sectionTitle?: T;
              items?:
                | T
                | {
                    icon?: T;
                    title?: T;
                    description?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        testimonialsBlock?:
          | T
          | {
              hidden?: T;
              sectionTitle?: T;
              testimonials?: T;
              id?: T;
              blockName?: T;
            };
        logoWall?:
          | T
          | {
              hidden?: T;
              sectionTitle?: T;
              awards?: T;
              id?: T;
              blockName?: T;
            };
      };
  metaTitle?: T;
  metaDescription?: T;
  metaImage?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  _order?: T;
  title?: T;
  slug?: T;
  sku?: T;
  brand?: T;
  ean?: T;
  ean2?: T;
  barcodeInternal?: T;
  category?: T;
  categoryName?: T;
  categorySlug?: T;
  categoryParentSlug?: T;
  categoryGrandparentSlug?: T;
  tagline?: T;
  rating?: T;
  reviewCount?: T;
  highlights?:
    | T
    | {
        title?: T;
        text?: T;
        id?: T;
      };
  badge?: T;
  productType?: T;
  price?: T;
  compareAtPrice?: T;
  externalUrl?: T;
  ctaLabel?: T;
  availability?: T;
  image?: T;
  gallery?:
    | T
    | {
        image?: T;
        id?: T;
      };
  compatibleWith?: T;
  specGroups?:
    | T
    | {
        groupLabel?: T;
        rows?:
          | T
          | {
              label?: T;
              value?: T;
              id?: T;
            };
        id?: T;
      };
  specs?:
    | T
    | {
        label?: T;
        value?: T;
        id?: T;
      };
  description?: T;
  metaTitle?: T;
  metaDescription?: T;
  sections?:
    | T
    | {
        keySpecStrip?:
          | T
          | {
              anchorLabel?: T;
              items?:
                | T
                | {
                    value?: T;
                    label?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        featureSection?:
          | T
          | {
              anchorLabel?: T;
              heading?: T;
              subheading?: T;
              subheadingPosition?: T;
              body?: T;
              image?: T;
              layout?: T;
              theme?: T;
              stats?:
                | T
                | {
                    value?: T;
                    label?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        tabbedShowcase?:
          | T
          | {
              anchorLabel?: T;
              heading?: T;
              intro?: T;
              layout?: T;
              tabs?:
                | T
                | {
                    label?: T;
                    image?: T;
                    caption?: T;
                    rows?:
                      | T
                      | {
                          icon?: T;
                          label?: T;
                          sublabel?: T;
                          value?: T;
                          id?: T;
                        };
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        bundleOptions?:
          | T
          | {
              anchorLabel?: T;
              heading?: T;
              options?:
                | T
                | {
                    label?: T;
                    price?: T;
                    comparePrice?: T;
                    externalUrl?: T;
                    product?: T;
                    isCurrent?: T;
                    soldOut?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        comparisonTable?:
          | T
          | {
              anchorLabel?: T;
              heading?: T;
              intro?: T;
              columns?:
                | T
                | {
                    product?: T;
                    label?: T;
                    image?: T;
                    tagline?: T;
                    price?: T;
                    comparePrice?: T;
                    ctaLabel?: T;
                    ctaUrl?: T;
                    highlight?: T;
                    id?: T;
                  };
              rows?:
                | T
                | {
                    label?: T;
                    values?:
                      | T
                      | {
                          value?: T;
                          id?: T;
                        };
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        inTheBox?:
          | T
          | {
              anchorLabel?: T;
              heading?: T;
              items?:
                | T
                | {
                    image?: T;
                    name?: T;
                    qty?: T;
                    id?: T;
                  };
              groups?:
                | T
                | {
                    label?: T;
                    items?:
                      | T
                      | {
                          image?: T;
                          name?: T;
                          qty?: T;
                          id?: T;
                        };
                    id?: T;
                  };
              defaultGroup?: T;
              caption?: T;
              id?: T;
              blockName?: T;
            };
        specTable?:
          | T
          | {
              anchorLabel?: T;
              heading?: T;
              id?: T;
              blockName?: T;
            };
        faqBlock?:
          | T
          | {
              anchorLabel?: T;
              heading?: T;
              items?:
                | T
                | {
                    question?: T;
                    answer?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        relatedProducts?:
          | T
          | {
              anchorLabel?: T;
              heading?: T;
              mode?: T;
              products?: T;
              id?: T;
              blockName?: T;
            };
        footnotes?:
          | T
          | {
              anchorLabel?: T;
              items?:
                | T
                | {
                    text?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        legalText?:
          | T
          | {
              anchorLabel?: T;
              heading?: T;
              body?: T;
              collapsed?: T;
              id?: T;
              blockName?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  _order?: T;
  title?: T;
  slug?: T;
  parent?: T;
  showInStrip?: T;
  stripBadge?: T;
  icon?: T;
  heroImage?: T;
  heroTagline?: T;
  banner?: T;
  description?: T;
  layout?:
    | T
    | {
        heroBanner?:
          | T
          | {
              hidden?: T;
              autoplaySeconds?: T;
              slides?:
                | T
                | {
                    badgeImage?: T;
                    eyebrow?: T;
                    eyebrowColor?: T;
                    heading?: T;
                    subheading?: T;
                    note?: T;
                    image?: T;
                    imageMobile?: T;
                    cta?:
                      | T
                      | {
                          label?: T;
                          url?: T;
                          newTab?: T;
                          style?: T;
                        };
                    align?: T;
                    theme?: T;
                    overlay?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        categoryStrip?:
          | T
          | {
              hidden?: T;
              categories?: T;
              id?: T;
              blockName?: T;
            };
        productCarousel?:
          | T
          | {
              hidden?: T;
              sectionTitle?: T;
              subtitle?: T;
              products?: T;
              cardStyle?: T;
              id?: T;
              blockName?: T;
            };
        bannerCarousel?:
          | T
          | {
              hidden?: T;
              heading?: T;
              cards?:
                | T
                | {
                    image?: T;
                    tag?: T;
                    heading?: T;
                    subheading?: T;
                    textTheme?: T;
                    buttons?:
                      | T
                      | {
                          label?: T;
                          url?: T;
                          style?: T;
                          id?: T;
                        };
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        bannerProductRow?:
          | T
          | {
              hidden?: T;
              sectionTitle?: T;
              showBanner?: T;
              banner?:
                | T
                | {
                    eyebrow?: T;
                    eyebrowColor?: T;
                    heading?: T;
                    subheading?: T;
                    priceNote?: T;
                    image?: T;
                    video?: T;
                    cta?:
                      | T
                      | {
                          label?: T;
                          url?: T;
                          newTab?: T;
                          style?: T;
                        };
                    theme?: T;
                  };
              products?: T;
              showMoreTile?: T;
              moreTile?:
                | T
                | {
                    label?: T;
                    url?: T;
                    image?: T;
                    description?: T;
                    secondaryLabel?: T;
                    secondaryUrl?: T;
                  };
              id?: T;
              blockName?: T;
            };
        promoCards?:
          | T
          | {
              hidden?: T;
              sectionTitle?: T;
              cards?:
                | T
                | {
                    heading?: T;
                    description?: T;
                    image?: T;
                    cta?:
                      | T
                      | {
                          label?: T;
                          url?: T;
                          newTab?: T;
                          style?: T;
                        };
                    theme?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        wideBanner?:
          | T
          | {
              hidden?: T;
              sectionTitle?: T;
              eyebrow?: T;
              eyebrowColor?: T;
              heading?: T;
              subheading?: T;
              priceNote?: T;
              image?: T;
              cta?:
                | T
                | {
                    label?: T;
                    url?: T;
                    newTab?: T;
                    style?: T;
                  };
              align?: T;
              theme?: T;
              id?: T;
              blockName?: T;
            };
        benefitsGrid?:
          | T
          | {
              hidden?: T;
              sectionTitle?: T;
              items?:
                | T
                | {
                    icon?: T;
                    title?: T;
                    description?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        testimonialsBlock?:
          | T
          | {
              hidden?: T;
              sectionTitle?: T;
              testimonials?: T;
              id?: T;
              blockName?: T;
            };
        logoWall?:
          | T
          | {
              hidden?: T;
              sectionTitle?: T;
              awards?: T;
              id?: T;
              blockName?: T;
            };
      };
  metaTitle?: T;
  metaDescription?: T;
  noindex?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "menu-panels_select".
 */
export interface MenuPanelsSelect<T extends boolean = true> {
  _order?: T;
  title?: T;
  slug?: T;
  mode?: T;
  category?: T;
  sections?:
    | T
    | {
        heading?: T;
        viewAllCategory?: T;
        viewAllLabel?: T;
        viewAllUrl?: T;
        featured?:
          | T
          | {
              product?: T;
              image?: T;
              title?: T;
              specLine?: T;
              url?: T;
              label?: T;
              ribbon?: T;
            };
        cards?:
          | T
          | {
              product?: T;
              image?: T;
              title?: T;
              specLine?: T;
              url?: T;
              label?: T;
              ribbon?: T;
              id?: T;
            };
        showViewAllTile?: T;
        viewAllTileUrl?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        banner?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        wide?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        content?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        large?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        full?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials_select".
 */
export interface TestimonialsSelect<T extends boolean = true> {
  _order?: T;
  author?: T;
  location?: T;
  quote?: T;
  image?: T;
  rating?: T;
  link?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "awards_select".
 */
export interface AwardsSelect<T extends boolean = true> {
  _order?: T;
  name?: T;
  logo?: T;
  url?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "subscribers_select".
 */
export interface SubscribersSelect<T extends boolean = true> {
  email?: T;
  subscribedAt?: T;
  status?: T;
  source?: T;
  consent?: T;
  note?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "backups_select".
 */
export interface BackupsSelect<T extends boolean = true> {
  label?: T;
  trigger?: T;
  includesMedia?: T;
  mediaFiles?: T;
  protected?: T;
  note?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects_select".
 */
export interface RedirectsSelect<T extends boolean = true> {
  from?: T;
  to?: T;
  reason?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  meta?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Тук се подрежда скелетът на менюто. Самите снимки и карти в мега менюто се редактират в раздел „Панели в менюто".
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: number;
  /**
   * Тънката сива лента НАД менюто — линк, промо текст и надпис за регион. Изключена по подразбиране. Полетата отдолу се пазят и когато е изключена.
   */
  utilityBarEnabled?: boolean | null;
  topLeftLabel?: string | null;
  topLeftUrl?: string | null;
  topPromoText?: string | null;
  topPromoUrl?: string | null;
  /**
   * Статичен текст. Оставете празно, за да го скриете.
   */
  regionLabel?: string | null;
  logo?: (number | null) | Media;
  /**
   * Показва се вдясно от логото, разделен с вертикална черта.
   */
  logoSuffix?: string | null;
  /**
   * Малкият текст под логото.
   */
  logoTagline?: string | null;
  /**
   * Главните точки в лентата. Точка без групи е обикновен линк, без мега меню.
   */
  items?:
    | {
        /**
         * Страницата, към която води точката. Адресът се извежда от категорията и следва преименуванията ѝ.
         */
        category?: (number | null) | Category;
        label: string;
        /**
         * Само ако точката води извън категориите.
         */
        url?: string | null;
        badge?: ('none' | 'hot' | 'new') | null;
        /**
         * Заглавията вляво в мега менюто, които се сгъват и разгъват. Напр. „Портативни електроцентрали".
         */
        groups?:
          | {
              heading: string;
              defaultOpen?: boolean | null;
              /**
               * Всяка подточка отваря панел вдясно. Панелите се редактират в раздел „Панели в менюто".
               */
              entries?:
                | {
                    /**
                     * Текстът на подточката се взима от заглавието на панела.
                     */
                    panel: number | MenuPanel;
                    id?: string | null;
                  }[]
                | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  searchEnabled?: boolean | null;
  ctaLabel?: string | null;
  ctaUrl?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  columns?:
    | {
        heading: string;
        links?:
          | {
              label: string;
              url: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  newsletterEnabled?: boolean | null;
  newsletterHeading?: string | null;
  newsletterText?: string | null;
  social?:
    | {
        platform: 'facebook' | 'instagram' | 'youtube' | 'linkedin' | 'tiktok';
        url: string;
        id?: string | null;
      }[]
    | null;
  copyright?: string | null;
  legalLinks?:
    | {
        label: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Цветовете на целия сайт. Празно поле означава „ползвай стойността по подразбиране“. Промяната се вижда веднага след запис — не е нужен нов билд.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "design".
 */
export interface Design {
  id: number;
  /**
   * Бутони и акценти. По подразбиране: #00a862
   */
  brand?: string | null;
  /**
   * По подразбиране: #00854e
   */
  brandDark?: string | null;
  /**
   * По подразбиране: #ffffff
   */
  page?: string | null;
  /**
   * По подразбиране: #ffffff
   */
  surface?: string | null;
  /**
   * По подразбиране: #f5f5f5
   */
  topbar?: string | null;
  /**
   * Сивите плочки в менюто и продуктовите мрежи. По подразбиране: #f2f2f2
   */
  tile?: string | null;
  /**
   * Ефектът на потъмняване. По подразбиране: #e8e8e8
   */
  tileHover?: string | null;
  /**
   * По подразбиране: #f0f0f0
   */
  navHover?: string | null;
  /**
   * По подразбиране: #ececec
   */
  navActive?: string | null;
  /**
   * По подразбиране: #1a1a1a
   */
  ink?: string | null;
  /**
   * По подразбиране: #6b6b6b
   */
  inkMuted?: string | null;
  /**
   * По подразбиране: #e3e3e3
   */
  line?: string | null;
  /**
   * По подразбиране: #c9c9c9
   */
  lineStrong?: string | null;
  /**
   * По подразбиране: #000000
   */
  night?: string | null;
  /**
   * По подразбиране: #121212
   */
  nightSoft?: string | null;
  /**
   * Промоции и баджове върху снимки. По подразбиране: #e2551f
   */
  accent?: string | null;
  /**
   * Етикет „Ново“ над име на продукт. По подразбиране: #1a6bd6
   */
  info?: string | null;
  /**
   * Етикети HOT и НОВО в главното меню. По подразбиране: #e0342b
   */
  alert?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  announcementEnabled?: boolean | null;
  announcementText?: string | null;
  announcementUrl?: string | null;
  logo?: (number | null) | Media;
  logoDark?: (number | null) | Media;
  /**
   * Заместете с точния фирмен цвят от брандбука. Използва се за бутони и акценти.
   */
  brandColor?: string | null;
  /**
   * Където водят бутоните за покупка, ако продуктът няма собствен линк.
   */
  shopUrl?: string | null;
  /**
   * Двойно обозначаване EUR / BGN по фиксирания курс 1.95583. Изисква се през преходния период след въвеждането на еврото.
   */
  showBgnPrices?: boolean | null;
  /**
   * Стои до задължителната отметка във формата за бюлетин. Изисква се от ЗЗЛД — затова е поле, а не зашит текст.
   */
  newsletterConsentText?: string | null;
  companyName?: string | null;
  vatNumber?: string | null;
  address?: string | null;
  phone?: string | null;
  email?: string | null;
  distributorNotice?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs-stats".
 */
export interface PayloadJobsStat {
  id: number;
  stats?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
  utilityBarEnabled?: T;
  topLeftLabel?: T;
  topLeftUrl?: T;
  topPromoText?: T;
  topPromoUrl?: T;
  regionLabel?: T;
  logo?: T;
  logoSuffix?: T;
  logoTagline?: T;
  items?:
    | T
    | {
        category?: T;
        label?: T;
        url?: T;
        badge?: T;
        groups?:
          | T
          | {
              heading?: T;
              defaultOpen?: T;
              entries?:
                | T
                | {
                    panel?: T;
                    id?: T;
                  };
              id?: T;
            };
        id?: T;
      };
  searchEnabled?: T;
  ctaLabel?: T;
  ctaUrl?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  columns?:
    | T
    | {
        heading?: T;
        links?:
          | T
          | {
              label?: T;
              url?: T;
              id?: T;
            };
        id?: T;
      };
  newsletterEnabled?: T;
  newsletterHeading?: T;
  newsletterText?: T;
  social?:
    | T
    | {
        platform?: T;
        url?: T;
        id?: T;
      };
  copyright?: T;
  legalLinks?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "design_select".
 */
export interface DesignSelect<T extends boolean = true> {
  brand?: T;
  brandDark?: T;
  page?: T;
  surface?: T;
  topbar?: T;
  tile?: T;
  tileHover?: T;
  navHover?: T;
  navActive?: T;
  ink?: T;
  inkMuted?: T;
  line?: T;
  lineStrong?: T;
  night?: T;
  nightSoft?: T;
  accent?: T;
  info?: T;
  alert?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  announcementEnabled?: T;
  announcementText?: T;
  announcementUrl?: T;
  logo?: T;
  logoDark?: T;
  brandColor?: T;
  shopUrl?: T;
  showBgnPrices?: T;
  newsletterConsentText?: T;
  companyName?: T;
  vatNumber?: T;
  address?: T;
  phone?: T;
  email?: T;
  distributorNotice?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs-stats_select".
 */
export interface PayloadJobsStatsSelect<T extends boolean = true> {
  stats?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskDailyBackup".
 */
export interface TaskDailyBackup {
  input?: unknown;
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}